### ISSUE TITLE
An issue!

### ISSUE THREAD

**Issue by audrow** [YesLets/learning-notebook-20211029#1]
No issue here, I'm just making an issue of there being no issue. Do you have an issue with that?

By the way, you can assign people you'd like to be responsible for things or add labels. It helps things stay organized.

**Comment by audrow** [comment]
PS, since this is a junk issue, you can close it out 😄

**Comment by YesLets** [comment]
What's a junk issue?

**Comment by YesLets** [comment]
by "Junk Issue" do you mean something of sentimental value? That's what I
found it googling so far.  The learning notebook was me working on the
homework you suggested ...
[image: image.png]
By "close it out" do you mean to archive it?

Liv

**Comment by audrow** [comment]
Haha, I mean that it's not a real issue: I'm not making a bug report or asking for a new feature. Although, you can keep it for sentimental value, if you like 😉 

You can close it by clicking the button beneath the comment box, either with or without a comment.

**Comment by YesLets** [comment]
closing now
