### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by audrow** [YesLets/learning-notebook-20211029#6]
For any public project, it is good to add a license. This makes it so that anyone who stumbles across your repository and wants to use what you've done knows if they can. This is especially important if people in companies want to use what they've done.

There are many open source licenses. I recommend the [MIT license](https://opensource.org/licenses/MIT) for its simplicity. You can find more information [here](https://opensource.org/licenses), if you like.

**Comment by YesLets** [comment]
MIT License added. Woohooo. That one was easy.  Yay
